version: '3.9'

services:
  boloes-web:
    build: .
    image: boloes-web:latest
    container_name: boloes-web
    restart: unless-stopped
    networks:
      - traefik_proxy
    expose:
      - '80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.boloes-http.rule=Host(`boloes.seudominio.com`)' 
      - 'traefik.http.routers.boloes-http.entrypoints=web'
      - 'traefik.http.routers.boloes-http.middlewares=redirect-to-https@file'
      - 'traefik.http.routers.boloes.rule=Host(`boloes.seudominio.com`)' 
      - 'traefik.http.routers.boloes.entrypoints=websecure'
      - 'traefik.http.routers.boloes.tls=true'
      - 'traefik.http.routers.boloes.tls.certresolver=letsencrypt'
      - 'traefik.http.services.boloes.loadbalancer.server.port=80'

networks:
  traefik_proxy:
    external: true
